name: fin_gpt
description: "A Flutter application with Firebase integration"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.0.0
  share_plus: ^11.0.0
  file_selector: ^1.0.3
  path_provider: ^2.0.15
  http: ^1.3.0
  lottie: ^3.3.1
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  flutter_hooks: ^0.21.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  crypto: ^3.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  firebase_app_check: ^0.3.2+5 # Downgrade to a stable version
  flutter_image_slideshow: ^0.1.3
  photo_view: ^0.14.0
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
          weight: 700
  uses-material-design: true