// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyBiMTA57IAArZYT9loGfxLYh8FRZuPS5jc',
    // appId: '1:651672711983:android:41e7cd17d3bc542a9f27da',
    // messagingSenderId: '651672711983',
    // projectId: 'fingpt-bbe3d',
    // storageBucket: 'fingpt-bbe3d.firebasestorage.app',
    apiKey: "AIzaSyA3e-v7vugeIJ4_G1kEq4BjaRZRTZ2ykLI",
    authDomain: "finance-58867.firebaseapp.com",
    projectId: "finance-58867",
    storageBucket: "finance-58867.firebasestorage.app",
    messagingSenderId: "493447811499",
    appId: "1:493447811499:web:54202fe1a3834c2e37c2ee",
    measurementId: "G-YFY58TXTME",
  );

}